apiVersion: v1
kind: Secret
metadata:
  name: rds-secret
  namespace: devops
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: YWRtaW4=        # base64("admin")
  SPRING_DATASOURCE_PASSWORD: YWRtaW4xMjMq    # base64("admin123*")

