apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: devops
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://devops.cfwus0g4m3bn.ap-south-1.rds.amazonaws.com:3306/devops"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_SHOW_SQL: "true"

