version: '3.8'

services:
  spring-backend:
    image: raji2306/spring-image:44
    container_name: spring-backend
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://devops.cfwus0g4m3bn.ap-south-1.rds.amazonaws.com:3306/devops
      - spring.datasource.username=admin
      - spring.datasource.password=admin123*
    networks:
      - mine

  react-frontend:
    build: ./react-frontend
    container_name: react-frontend
    ports:
      - "80:80"
    networks:
      - mine
    volumes:
      - vol:/app
    restart: always
    depends_on:
      - spring-backend

networks:
  mine:

volumes:
  vol:
