name: Deploy RDS

on:
  workflow_call:
    inputs:
      aws-access-key-id:
        required: true
        type: string
      aws-secret-access-key:
        required: true
        type: string
      rds-username:
        required: true
        type: string
      rds-password:
        required: true
        type: string
    outputs:
      rds_endpoint:
        description: "RDS endpoint"
        value: ${{ jobs.terraform.outputs.rds_endpoint }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    outputs:
      rds_endpoint: ${{ steps.output_rds.outputs.endpoint }}
    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ inputs.aws-access-key-id }}
          aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
          aws-region: ap-south-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.4

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        env:
          TF_VAR_db_username: ${{ inputs.rds-username }}
          TF_VAR_db_password: ${{ inputs.rds-password }}
        run: terraform apply -auto-approve

      - name: Show Outputs
        run: terraform output

      - name: Output RDS Endpoint
        id: output_rds
        run: |
          echo "endpoint=$(terraform output -raw rds_endpoint)" >> $GITHUB_OUTPUT
