name: EKS-Deploy-Test

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Springboot-React CI/CD"]
    types:
      - completed

jobs:
  create-eks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download RDS Endpoint Artifact
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: actions/download-artifact@v4
        with:
          name: rds-endpoint-final
          run-id: ${{ github.event.workflow_run.id }}
          path: ./rds-artifact

      - name: Read RDS Endpoint
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        run: |
          echo "RDS_ENDPOINT=$(cat ./rds-artifact/rds-endpoint.txt)" >> $GITHUB_ENV
          echo "RDS_ENDPOINT is $RDS_ENDPOINT"

      - name: Replace RDS Endpoint in Backend ConfigMap
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        run: |
          sed -i "s|jdbc:mysql://.*:3306/devops|jdbc:mysql://${RDS_ENDPOINT}:3306/devops|g" \
          sonic-integration/kubernetesManifest/backend/backend-configmap.yaml
          cat sonic-integration/kubernetesManifest/backend/backend-configmap.yaml


  #     - name: Configure AWS Credentials
  #       uses: aws-actions/configure-aws-credentials@v4
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-region: ap-south-1

  #     - name: Setup and deploy with eksctl
  #       run: |
  #           curl -sSL "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" \
  #             | tar xz && sudo mv eksctl /usr/local/bin/
          
  #           curl -sSLO "https://dl.k8s.io/release/$(curl -sSL https://dl.k8s.io/release/stable.txt)/bin/$(uname -s | tr '[:upper:]' '[:lower:]')/amd64/kubectl" \
  #             && chmod +x kubectl && sudo mv kubectl /usr/local/bin/

  #           eksctl version
  #           kubectl version --client

  #     - name: Create EKS Cluster
  #       run: |
  #         eksctl create cluster \
  #           --name devops-test \
  #           --version 1.29 \
  #           --region ap-south-1 \
  #           --nodes 2 \
  #           --node-type t2.medium \
  #           --with-oidc \
  #           --managed

  #     - name: Save kubeconfig
  #       run: |
  #         aws eks update-kubeconfig --region ap-south-1 --name devops-test
  #         cat ~/.kube/config > kubeconfig.yaml

  #     - name: Upload kubeconfig as artifact
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: kubeconfig
  #         path: kubeconfig.yaml

  # deploy-app:
  #   needs: create-eks
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v4

  #     - name: Download kubeconfig
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: kubeconfig
  #         path: .

  #     - name: Setup kubectl
  #       run: |
  #         mkdir -p ~/.kube
  #         mv kubeconfig.yaml ~/.kube/config
  #         chmod 600 ~/.kube/config

  #     # 🔹 Fetch RDS endpoint from artifact (must exist from previous workflow)
  #     - name: Download RDS endpoint
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: rds-endpoint
  #         path: .

  #     - name: Read RDS endpoint
  #       id: rds
  #       run: echo "rds_endpoint=$(cat rds-endpoint.txt)" >> $GITHUB_OUTPUT

  #     - name: Replace RDS endpoint in backend ConfigMap
  #       run: |
  #         sed -i "s|jdbc:mysql://.*:3306/devops|jdbc:mysql://${{ steps.rds.outputs.rds_endpoint }}:3306/devops|g" \
  #         sonic-integration/kubernetesManifest/backend/backend-configmap.yaml

  #     # ---- Apply manifests ----
  #     - name: Apply Namespace
  #       run: kubectl apply -f sonic-integration/kubernetesManifest/namespace.yaml

  #     - name: Apply Backend
  #       run: |
  #         kubectl apply -f sonic-integration/kubernetesManifest/backend/backend-configmap.yaml
  #         kubectl apply -f sonic-integration/kubernetesManifest/backend/backend-secret.yaml
  #         kubectl apply -f sonic-integration/kubernetesManifest/backend/backend-deployment.yaml
  #         kubectl apply -f sonic-integration/kubernetesManifest/backend/backend-service.yaml

  #     - name: Apply Frontend
  #       run: |
  #         kubectl apply -f sonic-integration/kubernetesManifest/frontend/frontend-nginx-configmap.yaml
  #         kubectl apply -f sonic-integration/kubernetesManifest/frontend/frontend-deployment.yaml
  #         kubectl apply -f sonic-integration/kubernetesManifest/frontend/frontend-service.yaml
  #         kubectl apply -f sonic-integration/kubernetesManifest/frontend/frontend-ingress.yaml

  #     - name: Sleep for pods to stabilize
  #       run: sleep 420   # 7 minutes

  #     - name: Check pods
  #       run: kubectl get pods -n devops

  #     # 🔹 Fetch ingress hostname
  #     - name: Get Ingress Hostname
  #       run: |
  #         kubectl get ingress -n devops -o jsonpath='{.items[0].status.loadBalancer.ingress[0].hostname}'
  #         kubectl get ingress -n devops
  #         echo ""
  
  # cleanup:
  #   needs: deploy-app
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Configure AWS Credentials
  #       uses: aws-actions/configure-aws-credentials@v4
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-region: ap-south-1

  #     - name: Install eksctl
  #       run: |
  #         curl --silent --location "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
  #         sudo mv /tmp/eksctl /usr/local/bin
  #         eksctl version

  #     - name: Delete EKS cluster
  #       run: eksctl delete cluster --region ap-south-1 --name devops-test
