name: Springboot-React CI/CD
run-name: Hexaware-Sonic-Run

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions: write-all

env:
  MYSQL_IMAGE: mysql-boom
  BACKEND_IMAGE: spring-image
  FRONTEND_IMAGE: react-image
  MYSQL_ROOT_PASSWORD: raji123*
  MYSQL_DATABASE: devops
  MYSQL_USER: raji
  MYSQL_PASSWORD: raji123*

jobs:
  build-backend:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: raji123*
          MYSQL_DATABASE: devops
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -p${MYSQL_ROOT_PASSWORD}"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v3

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..20}; do
            if mysql -h 127.0.0.1 -P 3306 -uroot -praji123* -e "SELECT 1;" &>/dev/null; then
              echo "✅ MySQL is ready!"
              break
            fi
            echo "⏳ Waiting for MySQL..."
            sleep 5
          done

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build Spring Boot app
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://127.0.0.1:3306/devops
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: raji123*
        run: mvn -B clean package --file ./spring-backend/pom.xml

      - name: Run Spring Boot app to initialize schema
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://127.0.0.1:3306/devops
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: raji123*
        run: |
          java -jar ./spring-backend/target/*.jar &
          APP_PID=$!
          echo "⏳ Waiting for Spring Boot to initialize schema..."
          sleep 20
          kill $APP_PID

      - name: Validate Database Tables
        run: |
          echo "📋 Databases:"
          mysql -h 127.0.0.1 -P 3306 -uroot -praji123* -e "SHOW DATABASES;"
          echo "📋 Tables in devops:"
          mysql -h 127.0.0.1 -P 3306 -uroot -praji123* -e "USE devops; SHOW TABLES;"
          echo "📋 Schema of user table:"
          mysql -h 127.0.0.1 -P 3306 -uroot -praji123* -e "USE devops; DESCRIBE user;"
          echo "📋 Rows in user table:"
          mysql -h 127.0.0.1 -P 3306 -uroot -praji123* -e "USE devops; SELECT * FROM user;"

      - name: Upload Backend Artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-jar
          path: ./spring-backend/target/*.jar

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: npm
          cache-dependency-path: ./react-frontend/package-lock.json  # 👈 Fix here
  
      - name: Install Dependencies & Build
        working-directory: ./react-frontend
        run: npm install
   
      # - name: Run Jest Tests
      #   working-directory: ./react-frontend
      #   run: npm test -- --ci --watchAll=false
  
      - name: Build Frontend
        working-directory: ./react-frontend
        run: CI=false npm run build
  
      - name: Upload Frontend Artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: ./react-frontend/build

  integration-test:
    needs: [build-backend]
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ env.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ env.MYSQL_DATABASE }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping -h 127.0.0.1" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v3
      
      - name: Download Backend Artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-jar
          path: .

      - name: Run Integration Tests
        working-directory: ./spring-backend
        run: mvn verify -Dspring.datasource.url=jdbc:mysql://127.0.0.1:3306/${{ env.MYSQL_DATABASE }}
        
  dockerize:
    needs: [build-backend, build-frontend, integration-test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download Backend Artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-jar
          path: ./spring-backend

      - name: Download Frontend Artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: ./react-frontend/build

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Backend Image
        run: |
          docker build -t raji2306/spring-image:${{ github.run_number }} ./spring-backend
          docker push raji2306/spring-image:${{ github.run_number }}

      - name: Build & Push Frontend Image
        run: |
          docker build -t raji2306/react-image:${{ github.run_number }} ./react-frontend
          docker push raji2306/react-image:${{ github.run_number }}

          sed -i "s|image: final-call|image: raji2306/spring-image:15|g" docker-compose.yaml
          sed -i "s|image: raji2306/react-app|image: raji2306/react-image:15|g" docker-compose.yaml
          sed -i "s|image: mysql-container|image: mysql:8.0|g" docker-compose.yaml

      - name: Run docker-compose
        run: |
            docker compose up -d
            docker compose ps

            echo "Waiting for backend to be healthy..."
            for i in {1..20}; do
              if docker exec backend curl -s http://localhost:8080/actuator/health | grep -q "UP"; then
                echo "✅ Backend is healthy!"
                break
              else
                echo "Waiting 5s..."
                sleep 5
              fi
            done

            echo "Checking frontend..."
            for i in {1..20}; do
              if docker exec frontend curl -s http://localhost:3000 | grep -q "<!DOCTYPE html>"; then
                echo "✅ Frontend is up!"
                break
              else
                echo "Waiting 5s..."
                sleep 5
              fi
            done

            echo "Checking MySQL..."
            for i in {1..20}; do
              if docker exec mysql-container mysqladmin ping -h "localhost" -uroot -p"${MYSQL_ROOT_PASSWORD}" | grep -q "mysqld is alive"; then
                echo "✅ MySQL is up!"
                break
              else
                echo "Waiting 5s..."
                sleep 5
              fi
            done
        env:
          MYSQL_ROOT_PASSWORD: ${{ env.MYSQL_ROOT_PASSWORD }}
